urls.py
from django.conf.urls import url, handler400, handler403, handler404, handler500
from . import views

#Custom Error Pages Routes
handler400 = views.handler400
handler403 = views.handler403
handler404 = views.handler404
handler500 = views.handler500

app_name = 'webcore'
urlpatterns = [

	#Default Pages Routes
	url(r'^$',  views.HomePageView.as_view(), name='home-page'),
	url(r'^aboutus/$', views.AboutUsPageView.as_view(), name = 'about-us'),
	url(r'^contactus/$', views.ContactUsPageView.as_view(), name = 'contact-us'),
	
	
	# #Email Campaign
	# url(r'^subscribe/$', views.AddEmailVerification.as_view(), name = 'verify-email-form'),
	# url(r'^subscribe/verify/(?P<verification_key>[\w-]+)/$', views.CheckEmailVerification.as_view(), name = 'verify-email-status'),
	# url(r'^subscribe/(?P<subscriber_id>\d+)/add/(?P<campaign_list>\d+)/$', views.UpdateNewsletterSubscription.as_view(), name = 'add-to-campaign'),
	# url(r'^unsubscribe/(?P<subscriber_id>\d+)/add/(?P<campaign_list>\d+)/$', views.UpdateNewsletterSubscription.as_view(), name = 'remove-from-campaign'),	#Banner
	
	
	#Category
	url(r'^category/$', views.CategoryListView.as_view(), name="webcore-category-List"),
	url(r'^category/add/$', views.CategoryCreateView.as_view(), name="webcore-category-create"),
	url(r'^category/(?P<slug>[\w-]+)/$', views.CategoryDetailView.as_view(), name="webcore-category-detail"),
	url(r'^category/(?P<slug>[\w-]+)/edit/$', views.CategoryUpdateView.as_view(), name="webcore-category-edit"),
	url(r'^category/(?P<slug>[\w-]+)/delete/$', views.CategoryDeleteView.as_view(), name="webcore-category-delete"),
	url(r'^categpry/(?P<pk>[\d]+)/$', views.CategoryDetailView.as_view(), name ="webcore-category-pk"),	

	#Pages
	# url(r'^create_page/$', views.PageCreateView.as_view(), name="webcore-page-create"),
	# url(r'^(?P<slug>[\w-]+)/$', views.PageDetailView.as_view(), name="webcore-page-detail"),
	# url(r'^(?P<slug>[\w-]+)/edit/$', views.PageUpdateView.as_view(), name="webcore-page-edit"),
	# url(r'^(?P<slug>[\w-]+)/delete/$', views.PageDeleteView.as_view(), name="webcore-page-delete"),
	# url(r'^(?P<pk>[\d]+)/$', views.PageDetailView.as_view(), name ="webcore-page-pk"),



	#Tag

#Default Apps Routes

]

webcore/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from allauth.account.models import EmailAddress
from allauth.socialaccount.models import SocialAccount
 

 def get_sentinnel_user():
	return get_user_model.objects.get_or_create(username="deleted")[0]

class Timestamp(models.Model):
	created_on = models.DateTimeField(auto_now = True)
	updated_on = models.DateTimeField(auto_now_add = True)
	published_date = models.DateTimeField(blank=True, null=True)
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.SET(get_sentinnel_user))
	draft = models.BooleanField(default = False)
	class Meta:
		abstract = True

	def publish(self):
		self.published_date = timezone.now()
		self.save()

class Musthave(Timestamp):
	title = models.CharField(max_length = 80, unique=True)
	slug = models.SlugField(unique = True)
	class Meta:
		abstract = True

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.name)
			super(Category, self).save(*args, **kwargs)


class Tag(Musthave):

	def get_absolute_url(self):
			return reverse_lazy('blog:blog_tag_view', kwargs={'slug': self.slug})


class Category(Musthave):
	parent = models.ForeignKey('self', null=True, blank=True)
	description = models.CharField(max_length = 60, null=True, blank = True)

	class Meta:
		verbose_name_plural = "categories"

	def get_subcategories(self):
		return self.objects.filter(
			parent_category__id=target_category.id)

	def get_parent(self):
		if self.parent is not None:
			return self.parent
		else:
			return None

	def get_absolute_url(self):
		return reverse_lazy('blog:blog_category', kwargs={'slug': self.slug})

class OnePageModel(Musthave):

	def clean(self):
		validate_only_one_instance(self)



#Default Pages Models
class About_website(OnePageModel):
	logo = models.ImageField(upload_to="website_logo")
	about = models.TextField()
	address = models.CharField(max_length=100)
	tel = models.CharField(max_length = 50)
	email = models.EmailField()

class Contact(OnePageModel):
	name = models.CharField(max_length = 30, null=True)
	email =models.EmailField()
	subject = models.CharField(max_length = 30)
	content = models.TextField()
	created = models.DateTimeField(auto_now = True, auto_now_add=False)
	updated = models.DateTimeField(auto_now = False, auto_now_add=True)

	def __str__(self):
		return( '%s - %s', self.email, self.subject)



class WebsitePage(models.Model):
	title = models.CharField(max_length = 100)
	slug = models.SlugField(unique = True)
	link = models.URLField()
	content = models.TextField()



class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    photo = models.ImageField(upload_to='profile_photo', null=True)
 
    def __str__(self):
        return "{}'s profile".format(self.user.username)
 
    class Meta:
        db_table = 'user_profile'
 
    def account_verified(self):
        if self.user.is_authenticated:
            result = EmailAddress.objects.filter(email=self.user.email)
            if len(result):
                return result[0].verified
        return False
 
User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


#Default Apps Models

class Banner(Musthave):
	desc = models.CharField(max_length = 60)
	btn_link = models.URLField()
	btn_title = models.CharField(max_length = 18)


class EmailMarketingSignUp(Timestamp):
	email = models.EmailField()
	active = models.BooleanField(default = False)

	def __str__(self):
		return self.email


class EmailMarketingConfirmed(TImestamp):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	activation_key = models.CharField(max_length=200)
	confirmed = models.BooleanField(default=False)

	def __str__(self):
		return self.confirmed

	def activate_user_email(self):
		activation_url = "%s%s" %(settings.SITE_URL, reverse("marketingactivation_view", args[self.activation_key]))
		context = {
			"activation_key": self.activation_key,
			"activation_url": activation_url,
			"user": self.user.first_name,
		}
		message = render_to_string("newslettersignup/activation_message.txt", context)
		subject = "Activate your email"
		self.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)

	def email_user(self, subject, message, from_email=None, **kwargs):
		send_mail(subject, message, from_email, [self.user.email], kwargs)




def validate_only_one_instance(obj):
	model = obj.__class__
	if (model.objects.count() > 0 and obj.id != model.objects.get().id):
		raise ValidationError("Can only create on instance of %s" % model.__name__)

templates/webcore/_shared/base.html
{% load static %}
<!DOCTYPE html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta property="og:url"                content="http://localhost:8000/" />
<meta property="og:type"               content="article" />
<meta property="og:title"              content="Check out this forecast on CASSIE: {{ poll.question }}"/>
<meta property="og:description"        content="Join Cassie to forecast this and more! See how accurate you are at \
                                                predicting the future!" />
<meta property="og:image"              content="{{MEDIA_URL }}/social/logo_words.png" />


<title>{% block head_title %} {{ page_title }} {% endblock %} | Work Flow</title>
<!-- Style Sheets -->
<link href="http://localhost/repo/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="{% static '/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Lato|Roboto' %}" rel="stylesheet">
<link href="{% static '/css/style.css' %}" rel="stylesheet">

<script src="http://localhost/repo/bower_components/jquery/dist/jquery.min.js"></script>
<script src="http://localhost/repo/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="http://localhost/repo/bower_components/fingerprintjs2/dist/fingerprint2.min.js"></script>
<script type="text/javascript">
	new Fingerprint2().get(function(result, components){
  console.log('result is', result); //a hash, representing your device fingerprint
  console.log('components are', components); // an array of FP components
});
</script>
<script src="{% static '/js/scripts.js' %}" ></script>


</head>

<body>
{% include 'webcore/_shared/navbar.html' %}
{% url 'webcore:home-page' as homepage_url %}
<section id="notices">
<div class="row">
	<div class="text-center">
		{% for msg in messages %}
			
	<div class="alert 
	{% if msg.tags == 'error' %} alert-danger {% elif msg.tags == 'debug' %} alert-warning 
	{% else %}  alert-{{msg.tags}} {% endif %} alert-dismissible fade in" role="alert">
    <div class="container">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
     <strong> {% if msg.tags == 'info' %} Please Note!
	{% elif msg.tags == 'success' %} Great!
	{% elif msg.tags == 'error' %} Oops!
	{% elif msg.tags == 'debug' %} Aw!
	{% endif %}</strong> {{msg}}
		</div>
    </div>
		{% empty %}

		{% endfor %}
	</div>
</div>
</section>

{% if page_header %}
{% include 'webcore/_shared/header.html' %}
{% endif %}
<section id="content">



	{% block content %}

	{% endblock %}

</section>
{% include 'webcore/_shared/footer.html' %}
{% include 'webcore/_shared/modal.html' %}
<script type="text/javascript">
	$('textarea').addClass('form-control');
	$('textarea').attr('placeholder', 'Type your text here...');
	$('textarea').attr('maxlength', '2600');
</script>
</body>
</html>

templates/webcore/_shared/footer.html
<section id="footer" class="text-center">
&copy <span id="copyright">
</span>
Workflow
</section>

templates/webcore/_shared/header.html
<section id='header'>
  <div class='jumbotron'>
    <div class='container'>
        {% block header %}
                <h2>{{page_header}} <br> {% if page_tagline %} <small>{{ page_tagline }}</small>{% endif %}</h2>
                {% if not request.user.is_authenticated %}
                <h3 class='text-left'>Enter your email address below</h3>
                <form class='form-inline' method='post' action='{% url 'accounts:get-invited' %}'>
                    {% csrf_token %}
                    <input type='text' class='form-control' placeholder='email' name='email'><button type='submit' class='btn btn-default'>Send invitation</button>
                </form>
                {% endif %}
        {% endblock %}
    </div>
  </div>
</section>

templates/webcore/_shared/modal.html
<div id="ajax-modal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" class="modal-body">

	      <div id="ajax-modal-content" class="paglr5">
	      </div>
    </div>
  </div>
</div>

templates/webcore/_shared/navbar.html
<nav class="navbar">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">WorkFLow</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" data-toggle="tooltip" data-placement="top" title="Home"><i class="fa fa-home" aria-hidden="true"></i></a></li>
       <li class="active"><a href="#" data-toggle="tooltip" data-placement="top" title="Projects"><i class="fa fa-suitcase" aria-hidden="true"></i><span class="sr-only">(current)</span></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-toggle="tooltip" data-placement="top" title="Notifications" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bell" aria-hidden="true"></i></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <li><a href="#" data-toggle="tooltip" data-placement="top" title="Teams"><i class="fa fa-users" aria-hidden="true"></i></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-toggle="tooltip" data-placement="top" title="Messages" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-envelope" aria-hidden="true"></i></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>

        <li><a href="#" data-toggle="tooltip" data-placement="top" title="Tasks"><i class="fa fa-tasks" aria-hidden="true"></i></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-toggle="tooltip" data-placement="top" title="My Account"  aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-gear" aria-hidden="true"></i> 
          </a>
          <ul class="dropdown-menu">
           {% if request.user.is_authenticated %}
           <li><a href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
           <li><a href="{% url 'accounts:userprofile' %}">My Profile</a></li>
           <li><a href="{% url 'accounts:userbank-details' %}">My Payment Information</a></li>
           <li role="separator" class="divider"></li>
           <li><a href="#">Programs</a></li>
           <li><a href="#">Support</a></li>
           <li role="separator" class="divider"></li>
           <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
           {% else %}
           <li><a href="{% url 'accounts:login' %}">Login</a></li>
           <li><a href="{% url 'accounts:get-invited' %}">Register</a></li>
           {% endif %}
         </ul>
       </li>
     </ul>
   </div><!-- /.navbar-collapse -->
 </div>

</nav>

{% comment "navbefore" %}
<nav class="navbar">
  <div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <i class="fa fa-bars"></i>
        </button>

  <a class="navbar-brand" href="{% url 'webcore:home-page' %}">revenupa.org</a>
  </div>
    <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'webcore:home-page' %}">Home<span class="sr-only">(current)</span></a></li>
            <li><a href="#">Ideology</a></li>
            <li><a href="{% url 'revprograms:program-list' %}">Programs</a></li>
            <li><a href="#">FAQ</a></li>
            <li><a href="{% url 'webcore:contact-us' %}">Contact Us</a></li>
          <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account<span class="caret"></span></a>
                <ul class="dropdown-menu">
                 {% if request.user.is_authenticated %}
                     <li><a href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
                    <li><a href="{% url 'accounts:userprofile' %}">My Profile</a></li>
                    <li><a href="{% url 'accounts:donatemethod-list' %}">My Payment Information</a></li>
                    <li role="separator" class="divider"></li>
                     <li><a href="#">Programs</a></li>
                    <li><a href="#">Support</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:register' %}">Register</a></li>
                {% endif %}
                </ul>
              </li>

          </ul>
    </div>
</nav>
{% endcomment %}